### PR TITLE
fix(edit): extract key comment before table header bracket

### LINKED ISSUE #691: Replacing an `InlineTable` with a comment with a `Table` results in invalid syntax
```rust
use std::str::FromStr;

use toml_edit::{Document, Item, Table};

fn main() {
    let mut val = Document::from_str(
        r#"
    # hello i'm a comment
    foo = { bar = 1 }
    "#,
    )
    .unwrap();
    println!("before: {}", val.to_string());
    let mut new_foo = Table::new();
    new_foo.insert("bar", Item::Value(1.into()));
    new_foo.insert("baz", Item::Value(2.into()));
    *val.get_mut("foo").unwrap() = Item::Table(new_foo);
    println!("after: {}", val.to_string());
}
```
Expected output:
```
before:
    # hello i'm a comment
    foo = { bar = 1 }

after:
    # hello i'm a comment
    [foo]
    bar = 1
    baz = 2
```
Actual output:
```
before:
    # hello i'm a comment
    foo = { bar = 1 }

after: [
    # hello i'm a comment
    foo ]
bar = 1
baz = 2
```

### PR DESCRIPTION
**Pull request by dimbleby**
A try at fixing #691.  I am in two minds about whether this is more of a sticking plaster than a real "fix".  But it is relatively tightly scoped - and seems to work. 

Fixes #691

### CODE REVIEW

File: crates/toml_edit/src/encode.rs [hunk 1]
```diff
@@ -37,16 +37,21 @@ fn encode_key_path(
     mut buf: &mut dyn Write,
     input: Option<&str>,
     default_decor: (&str, &str),
+    // Leaf decor to encode around the key path. When the leaf decor came from a
+    // key-value pair context (prefix already written before the opening bracket,
+    // suffix not meaningful inside `[...]`), pass `None` to skip it.
+    leaf_decor: Option<&Decor>,
```
Comment (epage) [inline crates/toml_edit/src/encode.rs]: If we move forward with this, I think passing in a `&Decor::default()` would be more correct than `None` as it would cause the default decor to be respected.

File: crates/toml_edit/tests/testsuite/edit.rs [hunk 2]
```diff
@@ -1681,3 +1681,53 @@ tool = { typst-test.tests = "tests" }
 "#]]
     );
 }
+
+#[test]
+fn inline_table_to_table_with_comment() {
```
Comment (epage) [inline crates/toml_edit/tests/testsuite/edit.rs:1788]: We generally ask that tests be added in a commit before a fix with them passing, reproducing the undesired behavior.  This helps illustrate the problem for anyone looking at this PR.

See also https://github.com/toml-rs/toml/blob/main/CONTRIBUTING.md#process

File: crates/toml_edit/src/encode.rs [hunk 3]
```diff
@@ -296,9 +315,17 @@ fn visit_table(
...
         };
+        let extracted = leaf_decor_before_bracket(path, input);
+        if let Some(leaf_decor) = extracted {
+            leaf_decor.prefix_encode(buf, input, DEFAULT_KEY_PATH_DECOR.0)?;
+        }
         table.decor.prefix_encode(buf, input, default_decor.0)?;
+        let leaf_decor = match extracted {
+            Some(_) => None,
+            None => path.last().map(|key| key.leaf_decor()),
+        };
```
Comment (epage) [inline crates/toml_edit/src/encode.rs]: I think I'd change this to where a function like `leaf_decor_before_bracket` returns
- `Option<Decor>` for before the table header
- `Decor` for the key in the table header

File: crates/toml_edit/tests/testsuite/edit.rs (hunk 2 above)
Comment (dimbleby) [reply crates/toml_edit/tests/testsuite/edit.rs:1788]: gonna need to resolve conflicts with my other PR anyway - both have tests at the end of the same file - so can do that.

**Comment by dimbleby** [comment]
rearranged, hopefully along the expected lines.  I introduced `Decor::EMPTY` so as to avoid the need to clone.
